local TechTree = require("techtree")

local seg_time = TUNING.SEG_TIME
local day_segs = TUNING.DAY_SEGS_DEFAULT
local dusk_segs = TUNING.DUSK_SEGS_DEFAULT
local night_segs = TUNING.NIGHT_SEGS_DEFAULT
local total_day_time = TUNING.TOTAL_DAY_TIME
local day_time = seg_time * day_segs
local dusk_time = seg_time * dusk_segs
local night_time = seg_time * night_segs

local wilson_attack = TUNING.BASE_SURVIVOR_ATTACK

--	Configs
	
	TUNING.POLAR_RETROFIT = GetModConfigData("biome_retrofit") or 0
	TUNING.POLAR_SHARD = GetModConfigData("biome_shard") or "forest"
	TUNING.POLAR_ICEGEN_CONFIG = GetModConfigData("polar_icegen") or 0
	TUNING.POLAR_BLIZZARDS_CONFIG = GetModConfigData("polar_blizzards") or 0
	TUNING.POLAR_WAVES_ENABLED = GetModConfigData("polar_snow") ~= false
	TUNING.POLAR_WORMHOLE_ENABLED = GetModConfigData("biome_wormhole") ~= false
	TUNING.POLAR_CC_ENABLED = GetModConfigData("misc_shader") ~= false
	
--	Worldgen
	
	TUNING.POLAR_TASKS_OPTIONALITY = {
		["Polar Floe"] = 0.5,
		["Polar Icerink"] = 0.25,
		["Polar Quarry"] = 0.32,
	}
	
	TUNING.POLARCAVES_MIGRATION_ID = 78.095
	
	TUNING.ANTLER_TREE_CHOPS = 10
	TUNING.ANTLER_TREE_CHOPS_REGEN_TIME = total_day_time
	TUNING.ANTLER_TREE_REGROWTH_TIME = total_day_time * 5
	TUNING.ANTLER_TREE_REGROWTH_TIME_MULT = 1
	TUNING.ANTLER_TREE_SAPLING_GROW_TIME = {base = 5 * day_time, random = 1 * day_time}
	
	TUNING.ICELETTUCE_REGROWTH_CHANCE = 0.25
	TUNING.ICELETTUCE_REGROWTH_MAX_QUANTITY = 10
	TUNING.ICELETTUCE_REGROWTH_MIN_QUANTITY = 3
	TUNING.ICELETTUCE_REGROWTH_TIME = {min = seg_time, max = total_day_time * 5}
	TUNING.ICELETTUCE_REGROWTH_SEASONS = {"summer"}
	
	TUNING.GRASS_POLAR_DENSITY = {min = 16, max = 30}
	TUNING.GRASS_POLAR_REEDS_CHANCE = 0.25
	TUNING.GRASS_POLAR_FLEA_CHANCE = 0.2
	TUNING.GRASS_POLAR_BLIZZARDPICK_CHANCE = 0.5
	
	TUNING.POLAR_ICICLE_DAMAGE = {
		SMALL = 200,
		MED = 250,
		LARGE = 300
	}
	TUNING.POLAR_ICICLE_MINE = 3
	TUNING.POLAR_ICICLE_BREAK_CHANCE = 0.33
	TUNING.POLAR_ICICLE_ENABLED = true
	TUNING.POLAR_ICICLE_GROWTIME = seg_time * 2
	TUNING.POLAR_ICICLE_GROWTIME_VARIANCE = total_day_time
	TUNING.POLAR_ICICLE_SPAWNTIME = seg_time
	TUNING.POLAR_ICICLE_ORNAMENT_CHANCE = 0.5
	TUNING.POLAR_ICICLE_NUMSHARDS = {
		bluegem = {min = 1, max = 2},
		bluegem_overcharged = {min = 2, max = 3},
	}
	TUNING.POLAR_MAX_ICICLES = 5
	TUNING.POLAR_WORLD_MAXICICLES = 100
	
	TUNING.POLAR_ROCK_MINE_TALL = 10
	
	TUNING.POLAR_SNOWMAN_DECOR = {
		HAT_CHANCE = 0.9,
		MAX_STACK = 3,
		STACK_CHANCES = {1, 0.8, 0.4},
		STACK_SIZES = {{2, 3}, {1, 3}, {1, 1}},
	}
	
	TUNING.TUMBLEWIND_SPAWNRATE_EARLY = 1
	TUNING.TUMBLEWIND_SPAWNRATE_LATER = 6
	TUNING.TUMBLEWIND_MAX_DENSITY = 10
	TUNING.TUMBLEWIND_WORLD_MAX = 20
	TUNING.TUMBLEWIND_ENABLED = true
	TUNING.TUMBLEWIND_NUMLOOT = 3
	TUNING.WINTER_FOOD_TUMBLEWIND_CHANCE = 0.2
	TUNING.WINTER_ORNAMENT_TUMBLEWIND_CHANCE = 0.1
	TUNING.FISHING_LURE_TUMBLEWIND_CHANCE = 0.05
	
--	Events
	
	TUNING.ARCTIC_FOOL_FISH_PRANK_CHANCE = 0.33
	TUNING.ARCTIC_FOOL_FISH_PRANK_PERIOD = 1
	TUNING.ARCTIC_FOOL_FISH_PRANK_RANGE = 8
	
	TUNING.ARCTIC_FOOL_FISH_BEAR_RANGE = 6
	TUNING.ARCTIC_FOOL_FISH_PRANKED_COOLDOWN = total_day_time
	TUNING.ARCTIC_FOOL_FISH_PRANKER_COOLDOWN = seg_time
	TUNING.ARCTIC_FOOL_FISH_PRANKER_MAX_DIST = 20
	TUNING.ARCTIC_FOOL_FISH_PRANKED_SANITY = 2.5
	TUNING.ARCTIC_FOOL_FISH_PRANKER_SANITY = 5
	TUNING.ARCTIC_FOOL_FISH_SANITY_MULT = 2
	
--	Players
	
	--TUNING.MIGHTINESS_POLAR_SLOWMULT = 1.5
	TUNING.MIGHTINESS_POLAR_SLOWTIME = 4
	--TUNING.WIMPY_POLAR_SLOWMULT = 0.75
	TUNING.WIMPY_POLAR_SLOWTIME = -1
	--TUNING.LEGDAY_POLAR_SLOWMULT = 1.25
	TUNING.LEGDAY_POLAR_SLOWTIME = 2
	
	TUNING.WX78_HEAT_SNOWBLOCK = 4
	TUNING.WX78_NAUGHTY_CHIPBOOSTS = {1, 2, 2.5, 3, 3.5, 4}
	
	--TUNING.WEREMODE_POLAR_SLOWMULT = 1.75
	TUNING.WEREMODE_POLAR_SLOWTIME = 2
	
	TUNING.WINONA_SPOTLIGHT_SNOWMELT_RANGE1 = 8
	TUNING.WINONA_SPOTLIGHT_SNOWMELT_RANGE2 = 10
	
--	Mobs
	
	TUNING.POLAR_MOOSE_HEALTH = 1000
	TUNING.POLAR_MOOSE_DAMAGE = 34
	TUNING.POLAR_MOOSE_DAMAGE_NOANTLER = 17
	TUNING.POLAR_MOOSE_ATTACK_PERIOD = 3
	TUNING.POLAR_MOOSE_ATTACK_RANGE = 1.5
	TUNING.POLAR_MOOSE_HIT_RANGE = 3
	TUNING.POLAR_MOOSE_ANTLER_HIT_RANGE = 5
	TUNING.POLAR_MOOSE_ANTLER_GROWTIME = total_day_time * 15
	TUNING.POLAR_MOOSE_ANTLER_TARGET_RANGE = 3
	TUNING.POLAR_MOOSE_SHED_MIN_DIST = 3
	TUNING.POLAR_MOOSE_SHED_MIN_VEL = 60
	TUNING.POLAR_MOOSE_SHED_WORK = 5
	TUNING.POLAR_MOOSE_RUN_SPEED = 12
	TUNING.POLAR_MOOSE_WALK_SPEED = 2.5
	TUNING.POLAR_MOOSE_KNOCK_RAD = 1.35
	TUNING.POLAR_MOOSE_RAM_MIN_DIST = 10
	
	TUNING.PENGUIN_GUARD_DAMAGE = 33
	TUNING.PENGUIN_GUARD_ATTACK_PERIOD = 2.5
	TUNING.PENGUIN_GUARD_ATTACK_DIST = 3
	TUNING.PENGUIN_GUARD_ATTACK_DIST_SHORT = TUNING.PENGUIN_ATTACK_DIST
	TUNING.PENGUIN_GUARD_HEALTH = 300
	TUNING.PENGUIN_GUARD_SPEAR_DROPRATE = 0.1
	
	TUNING.POLAR_PENGUIN_HERD_SPAWN_TIMES = {min = seg_time, max = day_time}
	TUNING.POLAR_PENGUIN_MAX_IN_RANGE = 20
	TUNING.POLAR_PENGUIN_SHORE_DIST = 11
	TUNING.POLAR_PENGUIN_MATING_SEASON_BABYDELAY = 8
	TUNING.POLAR_PENGUIN_MATING_SEASON_BABYDELAY_VARIANCE = 22
	
	TUNING.POLARBEAR_HEALTH = 800
	TUNING.POLARBEAR_HEALTH_REGEN_AMOUNT = 10
	TUNING.POLARBEAR_HEALTH_REGEN_PERIOD = (500 * 2) / (total_day_time * 3) * 10
	TUNING.POLARBEAR_DAMAGE = 50
	TUNING.POLARBEAR_DAMAGE_BITE = 75 -- 97
	TUNING.POLARBEAR_ATTACK_PERIOD = 2
	TUNING.POLARBEAR_BITE_PERIOD = 4
	TUNING.POLARBEAR_BITE_RANGE = 2.5
	TUNING.POLARBEAR_BITE_VEL = 22
	TUNING.POLARBEAR_RAGE_TIME = 12
	TUNING.POLARBEAR_RAGE_RUN_MULT = 1.5
	TUNING.POLARBEAR_RUN_SPEED = 6
	TUNING.POLARBEAR_WALK_SPEED = 3
	TUNING.POLARBEAR_HAT_CHANCE = 0.33
	TUNING.POLARBEAR_PLOWTIME = seg_time * 2
	TUNING.POLARBEAR_BLIZZARD_WARNTIME = total_day_time
	TUNING.POLARBEAR_BRAZIER_FUEL_MULT = 1.5
	TUNING.POLARBEAR_BRAZIER_REFUEL_COOLDOWN = seg_time * 3
	TUNING.POLARBEAR_BRAZIER_REFUEL_PERCENT = 0.25
	TUNING.POLARBEAR_PROTECTSTUFF_RANGE = 9
	TUNING.POLARBEAR_IGNORE_TREASURE_TIME = seg_time
	TUNING.POLARBEAR_MAJOR_SEARCH_RADIUS = 30
	
	TUNING.POLARBEAR_TREASURES = {
		houndstooth = {
			spoiled_fish_small = 3,
			fishmeat_small = 2,
		},
		walrus_tusk = {
			fishmeat = 2,
			fishmeat_small = 2,
			spoiled_fish = 1,
			oceanfish_medium_polar1_inv = 1,
			polarmoosehat = 0.5,
		},
		gnarwail_horn = {
			fishmeat = 2,
			oceanfish_medium_polar1_inv = 3,
			bluegem_shards = 0.5,
		},
		polarwargstooth = {
			fishmeat_small = 1,
			fishmeat = 3,
			oceanfish_medium_polar1_inv = 1,
			-- This also gives Brazier Blueprint if not learned yet
		},
		lavae_tooth = {
			bluegem_shards = 3,
			gnarwail_horn = 1,
			walrus_tusk = 1,
		},
	}
	TUNING.POLARBEAR_NUM_TREASURES = {
		houndstooth = 1,
		walrus_tusk = 3,
		gnarwail_horn = 3,
		polarwargstooth = 5,
		lavae_tooth = 6,
	}

	TUNING.POLARBEAR_LOYALTY_PER_HUNGER = TUNING.PIG_LOYALTY_PER_HUNGER / 2
	TUNING.POLARBEAR_LOYALTY_FISHMEAT_MULT = 3
	TUNING.POLARBEAR_LOYALTY_MAXTIME = TUNING.PIG_LOYALTY_MAXTIME / 2

	TUNING.POLARBEARKING_INFIGHTING_TOLARANCE = 10
	TUNING.POLARBEARKING_INFIGHTING_TOLARANCE_DRAIN = 5 -- Max possible tolarence drain from 1 hit polar bear (random from 0.5x to x)
	TUNING.POLARBEARKING_INFIGHTING_TOLARANCE_RESET_TIME = 8
	TUNING.POLARBEARKING_STOP_INFIGHTING_RANGE = 30
	
	TUNING.POLARBEARHOUSE_SPAWN_TIME = total_day_time * 4
	TUNING.POLARBEARHOUSE_ENABLED = true
	
	TUNING.POLARFOX_HEALTH = 200
	TUNING.POLARFOX_DAMAGE = 30
	TUNING.POLARFOX_RUN_SPEED = 8
	TUNING.POLARFOX_WALK_SPEED = 2.5
	TUNING.POLARFOX_LEADER_RUN_DIST = 14 * 14
	TUNING.POLARFOX_LOYALTY_PER_FOOD = total_day_time + seg_time
	TUNING.POLARFOX_LOYALTY_MAXTIME = total_day_time * 3
	TUNING.POLARFOX_HUNT_COOLDOWN = seg_time * 2
	
	TUNING.POLARFOX_SPAWN_TIME = total_day_time
	TUNING.POLARFOX_SPAWN_TIME_VARIATION = total_day_time
	TUNING.POLARFOX_MIN_SPAWN_POINTS = 6
	TUNING.POLARFOX_ENABLED = true
	
	TUNING.POLARWARG_HEALTH = 1300
	TUNING.POLARWARG_DAMAGE = 60
	
	TUNING.SHADOW_ICICLER_HEALTH = 200
	TUNING.SHADOW_ICICLER_DAMAGE = 35
	TUNING.SHADOW_ICICLER_ATTACK_PERIOD = 6
	TUNING.SHADOW_ICICLER_ATTACK_RANGE = 20
	TUNING.SHADOW_ICICLER_SPIKE_AMT = {min = 4, max = 9}
	TUNING.SHADOW_ICICLER_SPIKE_HEIGHT = {min = 8, max = 16}
	TUNING.SHADOW_ICICLER_SPIKE_RING_RANGE = {min = 4, max = 8}
	TUNING.SHADOW_ICICLER_SPIKE_RANGE = 2
	TUNING.SHADOW_ICICLER_SPEED = 4.4
	TUNING.SHADOW_ICICLER_SPAWN_CHANCE = 0.66
	
	TUNING.POLARFLEA_HEALTH = 60
	TUNING.POLARFLEA_DAMAGE = 10
	TUNING.POLARFLEA_ATTACK_PERIOD = 2
	TUNING.POLARFLEA_ATTACK_RANGE = 2
	TUNING.POLARFLEA_RUN_SPEED = 9
	TUNING.POLARFLEA_CHASE_RANGE = 10
	TUNING.POLARFLEA_HOST_RANGE = 10
	TUNING.POLARFLEA_HOST_FINDTIME = 20
	TUNING.POLARFLEA_HOST_MAXFLEAS = 4
	TUNING.POLARFLEA_HOST_MAXFLEAS_SMALL = 2
	TUNING.POLARFLEA_HOST_MAXFLEAS_LARGE = 8
	TUNING.POLARFLEA_HOST_HIT_DROPCHANCE = 0.1
	TUNING.POLARFLEA_HOST_REMOVE_DAMAGE = 10
	TUNING.POLARFLEA_HOUNDED_MIN = 0
	TUNING.POLARFLEA_HOUNDED_MAX = 3
	TUNING.POLARFLEA_INV_INSULATION = 20
	TUNING.POLARFLEA_FUNNYIDLE_CHANCE = {min = 0.4, added = 0.1}
	TUNING.POLARFLEA_STARVE_TIME = total_day_time * 20
	TUNING.POLARFLEA_POCKET_REGEN = 2
	TUNING.POLARFLEA_STORM_REGEN = -2
	TUNING.POLARFLEA_REGEN_RATE = 2
	TUNING.POLARFLEA_WORLD_MAXFLEAS = 100
	TUNING.POLARFLEA_INV_DAPPERNESS = -TUNING.DAPPERNESS_TINY
	
	TUNING.THRONE_KRAMPUS_DAMAGE_MULT = 0.5
	TUNING.THRONE_KRAMPUS_RANGE_MULT = 1.2
	TUNING.THRONE_KRAMPUS_SLEEP_TIME = 5
	TUNING.THRONE_KRAMPUS_STAY_ADD_TIME = 7.5 -- For each extra Krampi past 3
	TUNING.THRONE_KRAMPUS_STAY_TIME_MIN = 45
	TUNING.THRONE_KRAMPUS_STAY_TIME_MAX = 55
	TUNING.SPAWN_POLAR_THRONE = true
	
	TUNING.GIRL_WALRUS_HEALTH = 300
	TUNING.GIRL_WALRUS_DAMAGE = 22
	TUNING.GIRL_WALRUS_ATTACK_DIST = 3
	TUNING.GIRL_WALRUS_ATTACK_PERIOD = 4.4
	TUNING.GIRL_WALRUS_MAX_TRAPS = 3
	TUNING.GIRL_WALRUS_SPAWN_TRAP_COOLDOWN = 6
	TUNING.GIRL_WALRUS_SPAWN_CHANCES = {min = 0.2, max = 0.6}
	
	TUNING.WALRUSTRADES_REFRESH_TIMES = {min = total_day_time, max = total_day_time * 2}
	TUNING.WALRUSTRADES_RECIPE_BASE_CHANCE = 0.5
	
--  Bosses
	
	TUNING.EMPEROR_PENGUIN_HEALTH = 3500
	TUNING.EMPEROR_PENGUIN_DAMAGE = 40
	TUNING.EMPEROR_PENGUIN_DAMAGE_SPINMOD = 1
	TUNING.EMPEROR_PENGUIN_ATTACK_PERIOD = 2.6
	TUNING.EMPEROR_PENGUIN_ATTACK_DIST = 3
	TUNING.EMPEROR_PENGUIN_SPIN_COOLDOWN = 6
	TUNING.EMPEROR_PENGUIN_SPIN_DURATION = 5
	TUNING.EMPEROR_PENGUIN_SPIN_SPEEDMULT = {1.25, 1.5}
	TUNING.EMPEROR_PENGUIN_SUMMONS_HEALTH_PERCENT = {1, 0.8, 0.6, 0.4, 0.2}
	TUNING.EMPEROR_PENGUIN_SUMMONS_KILL_PERCENT = 0.75
	TUNING.EMPEROR_PENGUIN_SUMMONS_NUM = {3, 4, 5, 6, 7} --{3, 5, 7, 10, 14}
	TUNING.EMPEROR_PENGUIN_WALK_SPEED = 1
	TUNING.EMPEROR_PENGUIN_RUN_SPEED = 8
	
	TUNING.EMPEROR_PENGUIN_CASTLE_COLONY_MIN_AGE = total_day_time
	TUNING.EMPEROR_PENGUIN_CASTLE_COLONY_MIN_COOLDOWN = total_day_time * 0.5
	TUNING.EMPEROR_PENGUIN_CASTLE_RANGE = 20 -- Includes outdoor activity range
	TUNING.SPAWN_EMPEROR_PENGUIN = true
	TUNING.SPAWN_EMPEROR_PENGUIN_MOD = 1
	
	TUNING.FROSTY = {
		SIMPLE = {
			TARGETING_DIST = 10,
			TARGET_REMEMBER_TIME = 10,
			WALK_SPEED = 4,
			HEALTH = 6000,

			FLAMMABILITY = 0.33,

			MELEE_DAMAGE = 180,
			MELEE_COOLDOWN = 3.5,
			MELEE_RANGE = 3.5,
			MELEE_SPLASH_RANGE = 3,
			MELEE_FREEZE_POWER = 2,
			MELEE_SPLASH_DMG_PERCENT = 0.5,
			MELEE_PLAYER_DMG_PERCENT = 0.5,

			RANGED_DAMAGE = 60,
			RANGED_COOLDOWN = 7,
			RANGED_RANGE = 16,
			RANGED_SPLASH_RANGE = 3,

			BODY_SLAM_DAMAGE = 220,
			BODY_SLAM_COOLDOWN = 12,
			BODY_SLAM_HIT_RANGE = 4,
			BODY_SLAM_JUMP_RANGE = 4,
			BODY_SLAM_TARGET_RANGE = 16,
			BODY_SLAM_RUN_SPEED = 6.5,
			BODY_SLAM_PLAYER_DMG_PERCENT = 0.5,
			BODY_SLAM_FREEZE_POWER = 3,
			
			FROZEN_ARMOR_PROTECTION = 0.2,
			FROZEN_ARMOR_DURABILITY = 500,
			FROZEN_ARMOR_REGEN_TIME = 60,
			FROZEN_ARMOR_ONIGNITE_DAMAGE = 40,
			FROZEN_ARMOR_HEAT_MAX_DRAIN = 1,
			FROZEN_ARMOR_MAX_HEAT = 350
		},
		RAIDBOSS = {

		}
	}
		
--	Items
	
	TUNING.ANTLER_TREE_STICK_ATTACK_PERCENT = 0.004
	TUNING.ANTLER_TREE_STICK_DAMAGE = 48
	TUNING.ANTLER_TREE_STICK_PERISHTIME = total_day_time * 20
	TUNING.ANTLER_TREE_STICK_SPEED_MULT = 1.25
	TUNING.ANTLER_TREE_STICK_SLIPPINESS = TUNING.WILSON_RUN_SPEED * 2
	
	TUNING.COMPASS_POLAR_WOBBLE_MOD = 20
	
	TUNING.DRYICE_FREEZABLE_COLDNESS = 0.67
	TUNING.ICELETTUCE_COOLING = -5
	TUNING.ICELETTUCE_FREEZABLE_COLDNESS = 2
	TUNING.ICELETTUCE_KILLJOY_TOLERANCE = 0
	
	TUNING.ICICLESTAFF_DAMAGE = 25
	TUNING.ICICLESTAFF_ICICLES_NUM = 15
	TUNING.ICICLESTAFF_SANITY_DELTA = -1
	TUNING.ICICLESTAFF_USES = 25
	
	TUNING.POLARICESTAFF_FREEZE_TIME = 7
	TUNING.POLARICESTAFF_RANGE = 12
	TUNING.POLARICESTAFF_SANITY_DELTA = -1
	TUNING.POLARICESTAFF_USES = 20
	
	TUNING.ARMORPOLAR = 630
	TUNING.ARMORPOLAR_ABSORPTION = 0.85
	
	TUNING.ARMOR_POLARCROWNHAT = 420
	TUNING.ARMOR_POLARCROWNHAT_ABSORPTION = 0.7
	TUNING.ARMOR_POLARCROWNHAT_BREAK_CHANCE = 0.66
	TUNING.ARMOR_POLARCROWNHAT_BREAK_COOLDOWN = 10
	TUNING.ARMOR_POLARCROWNHAT_FREEZINESS = 0.1
	TUNING.ARMOR_POLARCROWNHAT_FREEZINESS_RANGE = 4
	TUNING.ARMOR_POLARCROWNHAT_FREEZINESS_RATE = 0.2
	
	TUNING.BOOK_RAIN_BLIZARD_DURATION = total_day_time
	
	TUNING.EMPEROR_PENGUINHAT_PERISHTIME = TUNING.PERISH_SUPERSLOW * 2.5
	
	TUNING.FROSTWALKERAMULET_FUEL = total_day_time * 1.5 -- Mostly behaving as finiteuses now
	TUNING.FROSTWALKERAMULET_FREEZE_TILE_USE = TUNING.FROSTWALKERAMULET_FUEL / 4000
	TUNING.FROSTWALKERAMULET_ICE_STAY_TIME = 8
	TUNING.FROSTWALKERAMULET_SLIPPINESS = TUNING.WILSON_RUN_SPEED * 9
	
	TUNING.POCKETWATCH_POLAR_COOLDOWN = total_day_time * 2
	
	TUNING.POLARAMULET = {
		GNARWAIL_HORN = {
			ANCHOR_RAISE_MULT = 1.2,
			ROW_FORCE_MULT = 0.5,
			ROW_MAX_VELOCITY = 0.5,
			SAIL_STRENGTH_SPEED = 5,
		},
		HOUNDSTOOTH = {
			DAMAGE_MULT = 0.1,
			MOVEMENT_SPEED = 0.05,
		},
		POLARWARGSTOOTH = {
			SNOWMOVEMENT_SPEED = 0.15,
			PERISHTIME = total_day_time * 5,
		},
		WALRUS_TUSK = {
			DAPERNESS = TUNING.DAPPERNESS_TINY,
			INSULATION = 80,
			LOYALTY_MULT = 2,
			SHADOW_LEVEL = 1,
		},
		LAVAE_TOOTH = {
			LAVAE_DAMAGE = 50,
			LAVAE_HEALTH = 500,
			STARVED_DAMAGE = 25,
			STARVED_RATE = 200 / total_day_time,
			
			HOUNDSTOOTH_DAMAGE = 25,
			GNARWAIL_HORN_SPEED_MULT = 0.2,
			POLARWARGSTOOTH_FREEZINESS = 1,
			POLARWARGSTOOTH_STARVE_RATE_MULT = 0.66,
			WALRUS_TUSK_HEALTH = 500,
			
			PERISHTIME = total_day_time * 2,
			FIRE_RESIST = 0.3,
		},
	}
	TUNING.POLARAMULET_PERISHTIME = total_day_time * 5
	
	TUNING.POLARBEARHAT_PERISHTIME = total_day_time * 3
	
	TUNING.POLARMOOSEHAT_PERISHTIME = total_day_time * 5
	
	TUNING.POLARFLEA_SACK_CALL_DIST = TUNING.POLARFLEA_HOST_RANGE
	TUNING.POLARFLEA_SACK_PERISHTIME = total_day_time * 10
	TUNING.POLARFLEA_SACK_PRESERVER_RATE = 0
	
	TUNING.POLAR_SPEAR_DAMAGE = TUNING.SPEAR_DAMAGE
	
	TUNING.WALRUS_BAGPIPE_PERISHTIME = TUNING.ONEMANBAND_PERISHTIME * 2
	
	TUNING.WALRUS_BEARTRAP_DAMAGE = 30
	TUNING.WALRUS_BEARTRAP_RADIUS = 1.1
	TUNING.WALRUS_BEARTRAP_AUTOSTRUGGLE_TIMES = {min = 0.6, max = 3, lastattacked = 2}
	TUNING.WALRUS_BEARTRAP_STRUGGLE_DAMAGE = 2.5
	TUNING.WALRUS_BEARTRAP_STRUGGLES_REQUIRED = {min = 2, max = 4, unlucky_added = 2, mob_added = 3}
	TUNING.WALRUS_BEARTRAP_SNOW_SEE_DIST = 5
	TUNING.WALRUS_BEARTRAP_TEMP_MASS_OVERRIDE = 300
	TUNING.WALRUS_BEARTRAP_USES = 10
	TUNING.WALRUS_BEARTRAP_VISILITY_SNOWDISTS = {min = 1, max = 7}
	
	TUNING.WINTERS_FISTS_DURABILITY = 125
	TUNING.WINTERS_FISTS_ICE_REPAIR = 125 / 25
	TUNING.WINTERS_FISTS_DAMAGE = wilson_attack * 1.25
	TUNING.WINTERS_FISTS_DAMAGE_SNOWBALL = TUNING.WINTERS_FISTS_DAMAGE * 9
	TUNING.WINTERS_FISTS_SLOW = 0.9
	TUNING.WINTERS_FISTS_SPELL_TYPES = 3
	TUNING.WINTERS_FISTS_SNOWBALL_COLDNESS = 0.25
	TUNING.WINTERS_FISTS_SNOWBALL_GIANT_COLDNESSPERCENT = 0.9
	TUNING.WINTERS_FISTS_SNOWBALL_COOLDOWN = 0.75
	TUNING.WINTERS_FISTS_SNOWBALL_GIANT_GROGGINESS = 1
	TUNING.WINTERS_FISTS_SNOWBALL_GIANT_KO_TIME = 1
	TUNING.WINTERS_FISTS_SNOWBALL_GIANT_WORKS = 5
	TUNING.WINTERS_FISTS_SNOWBALL_MED_WORKS = 1
	TUNING.WINTERS_FISTS_TERRAFORMER_COOLDOWN = 10
	TUNING.WINTERS_FISTS_TERRAFORMER_DURATION = seg_time * 2
	TUNING.WINTERS_FISTS_TERRAFORMER_RAD = 1
	
	TUNING.OCEANFISH_IN_ICE_HATCH_CRACK_TIME = 3
	TUNING.OCEANFISH_IN_ICE_HATCH_TIME = seg_time
	TUNING.OCEANFISH_IN_ICE_SPAWN_CHANCE = 0.025
	
	TUNING.POLARICEPACK_PRESERVE_MULT = 0.75
	
	TUNING.HEATROCK_INSULATION_POLARMULT = 0.5
	
	TUNING.GOLD_VALUES.POLARTRINKETS = {
		5, --[1] Snuggy Gnome
		5, --[2] Snuggy Gnomette
	}
	
	TUNING.WINTERS_FEAST_TREE_DECOR_LOOT.EMPEROR_PENGUIN = {basic = 2, special = "winter_ornament_boss_emperor_penguin"}
	
--	Buffs
	
	TUNING.FREEZABLE_INSULATION_MAX_RESISTANCE = 5
	TUNING.FREEZABLE_INSULATION_STEP = 120
	TUNING.FREEZABLE_INSULATION_STEP_AMOUNT = 0.5
	TUNING.FREEZABLE_BELLY_MULT_MAX = 2
	TUNING.FREEZABLE_BELLY_MULT_MIN = 0.5
	TUNING.FREEZABLE_BELLY_MULT_RANGE = TUNING.HOT_FOOD_BONUS_TEMP
	
	TUNING.MOARHUNT_BUFF_DURATION = total_day_time * 2
	TUNING.MOARHUNT_BUFF_NUMTRACKS_MULT = 0.5
	
	TUNING.POCKETWATCH_BUFF_DURATION = total_day_time
	TUNING.POCKETWATCH_BUFF_TICK = 0.06
	TUNING.POCKERWATCH_BUFF_DRAINS = {
		health 		= 6,
		hunger 		= 0.15,
		sanity 		= 1,
		temperature = 0.01,
		moisture 	= 2,
	}
	
	TUNING.POLAR_IMMUNITY_DURATION = total_day_time * 1.1
	TUNING.POLAR_IMMUNITY_DURATION_LONG = total_day_time * 2.2
	TUNING.POLAR_IMMUNITY_DURATION_SHORT = seg_time * 4
	
	TUNING.POLAR_WETNESS_LVLS = 6
	TUNING.POLAR_WETNESS_LVL_WETNESS = -0.2
	TUNING.POLAR_WETNESS_MIN_PROOFNESS = 1
	TUNING.POLAR_WETNESS_MAX_INSULATION = 120
	TUNING.POLAR_WETNESS_OVERHEATS = 36
	TUNING.POLAR_WETNESS_SNIFFNESS = 0.12
	TUNING.POLAR_WETNESS_TEMP_MODIFIER = 999
	
	TUNING.POLARWETNESS_DEBUFF_FIRE_RESIST = 0.33
	TUNING.POLARWETNESS_DEBUFF_TEMP_MODIFIER = -3.35
	TUNING.POLARWETNESS_DEBUFF_TICK = 0.5
	TUNING.POLARWETNESS_DEBUFF_STARTTEMP = TUNING.POLAR_WETNESS_OVERHEATS
	
	TUNING.POLAR_WALRUSALLY_BUFF_DURATION = 15
	TUNING.POLAR_WALRUSBOOST_BUFF_DURATION = 5
	TUNING.POLAR_WALRUSBOOST_PREPTIME = 4
	TUNING.POLAR_WALRUSBOOST_COOLDOWN = seg_time
	
--	Buildings
	
	TUNING.POLARAMULET_STATION_SPEAKTIME = 2
	
	TUNING.POLARBEARHOUSE_ENABLED = true
	TUNING.POLARBEARHOUSE_SPAWN_TIME = total_day_time * 4
	
	TUNING.POLAR_BRAZIER_FUEL_MAX = TUNING.CAMPFIRE_FUEL_MAX
	TUNING.POLAR_BRAZIER_BLUEPRINT_CHANCE = 0.1
	TUNING.POLAR_BRAZIER_HOUSE_SPAWN_CHANCE = 0.5
	
	TUNING.POLARICE_PLOW_USES = 8
	TUNING.POLARICE_PLOW_DRILLING_DURATION = 6
	TUNING.POLARICE_PLOW_PONDDIST = 2
	TUNING.POLARICE_PLOW_PONDTIME = total_day_time * 2
	
	TUNING.POLARWALL_HEALTH = 600
	TUNING.POLARWALL_FREEZE_INSULATION_MIN = 100
	
	TUNING.POLAR_THRONE_GIFTRING_DIST = 7.8
	TUNING.POLAR_THRONE_GIFTRING_MAX_OFFSET = 6
	TUNING.POLAR_THRONE_EZ_REFRESH = false -- In throne worldsetting (enabled in custom start), if enabled gifts refresh all years without opening stash manually
	
	TUNING.RAINOMETER_BLIZZARD_WARNTIME = total_day_time * 2
	TUNING.WINTEROMETER_BLIZZARD_WARNTIME =  total_day_time * 3
	
--	Misc
	
	TUNING.FROSTY_SNOWBALL_SPEED_NEAR = 16
	TUNING.FROSTY_SNOWBALL_GRAVITY_NEAR = -80
	TUNING.FROSTY_SNOWBALL_SPEED_FAR = 20
	TUNING.FROSTY_SNOWBALL_GRAVITY_FAR = -55
	TUNING.FROSTY_SNOWBALL_SPEED_VERYFAR = 22
	TUNING.FROSTY_SNOWBALL_GRAVITY_VERYFAR = -40
	TUNING.FROSTY_SNOWBALL_FREEZE_POWER = 3
	
	TUNING.ANCHOR_DEPTH_TIMES.POLAR = 5
	
	TUNING.OCEAN_POLAR_CONVERT_RANGE = 15
	
	TUNING.OCEANFISH_SHOAL.POLAR_CHILD_REGENPERIOD = TUNING.OCEANFISH_SHOAL.CHILD_REGENPERIOD * 3.33
	TUNING.OCEANFISH_SHOAL.POLAR_MAX_CHILDREN = TUNING.OCEANFISH_SHOAL.MAX_CHILDREN / 2
	
	TUNING.DEEP_IN_SNOW_PLAYERDIST = 8
	TUNING.POLAR_SLOWMULT = 0.6
	TUNING.POLAR_SLOWTIME = 8
	TUNING.POLAR_COVERTIME = {min = 3, max = 10}
	TUNING.POLAR_SNOW_MELT_TEMP = 54
	TUNING.POLAR_SNOW_UPDATE_RATE = 1
	
	TUNING.HUNT_ALTERNATE_POLAR_CHANCE_MIN = 0 -- AKA: 100% chances for Moose in Summer
	TUNING.HUNT_ALTERNATE_POLAR_CHANCE_MAX = 0.66 -- Chances for Ice Varg in Winter
	TUNING.HUNT_ALTERNATE_POLAR_CHANCE = TUNING.HUNT_ALTERNATE_BEAST_CHANCE_MAX -- Chances for Ice Varg outside of Winter (33%)
	TUNING.HUNT_KOALEFANT_POLAR_CHANCE = 0.5
	
	TUNING.SNOW_PLOW_RANGES = {
		REPLACED = 3, -- Deployed / Built something in snow
		USED = 4, -- Crafting Dry Ice
		SHOVEL = 5,
		GOLDENSHOVEL = 6,
		SHOVEL_LUNARPLANT = 7,
		SNOW_EMOTE = 4, -- /snowangel
	}
	
	TUNING.POLAR_SNOW_FORGIVENESS = {
		PLOWING = -1,
		SNOWWAVE = -1,
	}
	
	TUNING.POLARPLOW_BLOCKER_DURATION = total_day_time - (seg_time * 2)
	TUNING.POLARPLOW_BLOCKER_DURATION_FIRE = seg_time * 2
	TUNING.POLARPLOW_BLOCKER_DURATION_GRADUAL = seg_time * 4
	TUNING.POLARPLOW_BLOCKER_CANADIAN_MULT = 2
	TUNING.POLARPLOW_BLOCKER_STORMCUT_MULT = 0.25
	TUNING.POLARPLOW_USE = 0.5 -- Twice less durability used than digging up
	
	TUNING.SHADE_POLAR_RANGE = 22
	TUNING.SHADE_POLAR_SCALE = 3.8
	
	TUNING.POLAR_STORM_COOLDOWN_MIN = total_day_time * 5
	TUNING.POLAR_STORM_COOLDOWN_MAX = total_day_time * 15
	TUNING.POLAR_STORM_LENGTH_MIN = total_day_time * 0.5
	TUNING.POLAR_STORM_LENGTH_MAX = total_day_time * 1.5
	TUNING.POLAR_STORM_TEMP_MODIFIER = -10
	
	TUNING.POLAR_STORM_FUELEDMULT = {
		CAMPFIRE = 4,
		FIREPIT = 2,
		TORCH = 3,
	}
	
	TUNING.POLAR_STORM_PROTECTION = {
		CROWN = 6,
		CAMPFIRE = 6,
		FIRE = 8,
		TORCH = 2, -- Unused, in hand fires now give fixated level
	}
	
	TUNING.SNOW_BLOCK_RANGES = {
		FIRE = 8,
		FIRE_SMALL = 5,
		STAR = 10,
		CREATURE = 8,
		TORCH = 4, -- Thrown torch
		TORCH_BRIGHTNESS_SKILL = 0.67,
		
		FIREFX_LEVEL_MULTS = { -- Unique modifier for burnables based on fuel / flame size
			LVL1 = 0.5,
			LVL2 = 0.75,
			LVL3 = 1,
			LVL4 = 1.25,
		},
	}
	
	TUNING.POLAR_STORM_LIGHTER_LEVEL = 0.5
	TUNING.POLAR_STORM_BEARHEAD_LEVEL = 0.8
	
	TUNING.TRAP_POLARTEETH_DAMAGE = TUNING.TRAP_TEETH_DAMAGE * 2
	TUNING.TRAP_POLARTEETH_FREEZING = 6
	TUNING.TRAP_POLARTEETH_USES = TUNING.TRAP_TEETH_USES * 5
	
	TUNING.POLAR_MIST_TIME = 15
	TUNING.POLAR_MIST_TWEENTIME = 1.5
	
	TUNING.SNOWED_SHADER_MAX_SUBMERGE = -0.6 -- LukaS: Distance, in in-game units (4 = tile), to shift the player model on the Y axis
	TUNING.SNOWED_SHADER_MAX_FREEZE = 0.55
	
	TUNING.KLAUSSACK_POLAR_STACKSIZES = {
		goose_feather = 5,
		townportaltalisman = 3,
	--	tallbirdegg = 0, lol
	}
	
--	Tech
	
	TUNING.PROTOTYPER_TREES.POLARAMULET_STATION = TechTree.Create({
		POLARAMULET_STATION = 2,
	})
	
	TUNING.PROTOTYPER_TREES.WANDERINGWALRUSSHOP = TechTree.Create({
		WANDERINGWALRUSSHOP = 2,
	})

	TUNING.PROTOTYPER_TREES.POLARBEARKING_TRIALS = TechTree.Create({
		POLARBEARKING_TRIALS = 2,
	})