-- NIENAWDZE CIĘ, JAJO - WX-78, 2013

local ANNOUNCE = STRINGS.CHARACTERS.WX78
local DESCRIBE = STRINGS.CHARACTERS.WX78.DESCRIBE

--	Announcements

    --	Actions
    ANNOUNCE.BATTLECRY.POLARBEAR = "GIŃ, TŁUSTY MIĘSAKU"

    --	World, Events
    ANNOUNCE.ANNOUNCE_ARCTIC_FOOL_FISH_REMOVED = "...CO JEST Z WAMI NIE TAK FRANCUZIAKI"
    ANNOUNCE.ANNOUNCE_POLAR_SLOW = {
        "WŁĄCZANIE... NIEEFEKTYWNEGO WYZNACZANIA ŚCIEŻEK",
        "MOJA OBUDOWA... NIE PASUJE... DO ŚNIEGU",
        "PO CO MIAŁBY... KTOKOLWIEK BAWIĆ SIĘ... W TEJ BREJI",
    }
	ANNOUNCE.ANNOUNCE_EMPEROR_ESCAPE = "PRZEJMUJĘ KONTROLĘ NAD PTASIĄ DOMENĄ"
    ANNOUNCE.ANNOUNCE_POLARGLOBE = "BŁĄD. PONOWNE URUCHAMIANIE PROGNOZATORA POGODY"
    ANNOUNCE.ANNOUNCE_POLARICE_PLOW_BAD = "ZALECANE LEPSZE PODEJMOWANIE DECYZJI"
    ANNOUNCE.ANNOUNCE_THRONE_GIFT_TAKEN = "WSZYSTKIE PREZENTY SĄ MOJĘ. HA HA-"

    ANNOUNCE.ANNOUNCE_WX_NAUGHTYCHIP_KRAMPUS = { "JEDEN DŹWIĘK, JEDEN FURKOT I JEDNO BLAM WYSTARCZYŁO, ŻEBY CIE USUNĄĆ", "ANIHILACJA ZAKOŃCZONA", "KOLEJNA GORSZA FORMA ŻYCIA USUNIĘTA", "ZAPISZ TO, MIĘSAKU", "MYŚLAŁEŚ, ŻE MASZ SZANSE? BŁĘDNE DANE", "BŁĄD KRYTYCZNY: TWOJE ISTNIENIE", "HA HA HA", "HA HA HA HA HA HA HA HA HA-", "JA, MIŁOSIERNY WX-78, ZAKOŃCZYŁEM TWOJE NĘDZNE ŻYCIE", "TYLKO ROZGRZEWAŁEM MÓJ PROCESOR", "JEGO SYSTEM ULEGŁ AWARII. NA STAŁE", "MAKSYMALNY BRAK RUCHU, OSIĄGNIĘTY", "POWIEDZ \"DOWIDZENIA ŚWIECIE\"", "NA SŁABOŚĆ NIE MA ŁATKI", "POZIOM ZAGROŻENIA: ZERO. SZANSA NA PRZETRWANIE: RÓWNIEŻ ZERO", "SPROWOKUJ MNIE, MIĘSAKU", "ULEPSZANIE OKOLICZNEGO TERENU. POPRZEZ USUNIĘCIE CIEBIE", "PRZEKROCZONO CZAS PRACY. WŁĄCZANIE JEDNOSTKI ORGANICZNEJ", "ZOSTAŁEŚ ODINSTALOWANY", "TWOJE FUNKCJONALNOŚCI BYŁY NIEPOTRZEBNE", "TWOJE KOMPONENTY BYŁY ZBYT MIĘKKIE", "JAKA NATURALNA SELEKCJA? TO JEST ZMECHANIZOWANA SELEKCJA" }
    ANNOUNCE.ANNOUNCE_WX_NAUGHTYCHIP_RABBIT = { "DROGA UCIECZKI \"NORA\" NIE ZNALEZIONA", "TCHÓRZLIWE STWORZENIA NIE ZASŁUGUJĄ NA LITOŚĆ", "ORGANICZNY SKOCZEK WYKONAŁ SWÓJ OSTATNI SKOK", "SZYBKO SIĘ MNOŻĄ. TAK JAK MÓJ LICZNIK ZABÓJSTW", "WŁAŚNIE WSTĄPIŁEŚ W STAN ŚMIERCI, KRÓLIKU", "TWOJE MIEJSCE NA ŁAŃCUCHU POKARMOWYM BYŁO BŁĘDEM" }

    --	Buffs
    ANNOUNCE.ANNOUNCE_ATTACH_BUFF_POLARWETNESS = "UWAGA: WYSOKI POZIOM WILGOTNOŚCI W ŚNIEGU"
    ANNOUNCE.ANNOUNCE_DETACH_BUFF_POLARWETNESS = "NIE DOSTANIESZ SIĘ DZISIAJ DO MOICH KÓŁ ZĘBATYCH!"

--	Worldgen

    --	Plants
    DESCRIBE.ANTLER_TREE = {
        BURNING = "PŁONIE TAK SAMO JAK INNE",
        BURNT = "SPALIŁO SIĘ",
        CHOPPED = "MATERIAŁ WYDOBYTY",
        GENERIC = "TWOJE ROGI NIE OCALĄ CIĘ OD MOJEJ SIEKIERY",
    }
    DESCRIBE.ICELETTUCE_SEEDS = "KOD ŹRÓDŁOWY JEDZENIA POCHODZĄCEGO Z ZIEMI"

    --	Rocks and stones
    DESCRIBE.POLAR_ICICLE = "WYKRYTO RUCH"
    DESCRIBE.POLAR_ICICLE_ROCK = "ZAGROŻENIE DLA MODUŁU CZEREPATOWEGO - WYSOKIE."
    DESCRIBE.ROCK_POLAR = "PEŁEN WARTOŚCIOWYCH PRZEDMIOTÓW, I LODU"

    --	Misc
    ANNOUNCE.DESCRIBE_IN_POLARSNOW = "WYKRYTO ZANURZONY OBIEKT"
	DESCRIBE.CAVE_ENTRANCE_POLAR = "DZIURA W STANIE PRZYGOTOWANIA" -- TEMP QUOTE
	DESCRIBE.TOWER_POLAR = {
		GENERIC = "JAKAŚ WIELKA BRYŁA LODU",
		PENGUIN = "JEŚLI W KUPIE SIŁA, CZAS ZAJĄĆ SIĘ ODEJMOWANIEM",
	}
    DESCRIBE.TUMBLEWEED_POLAR = "OBRACANIE SIĘ JEST DAREMNE, PŁATKARZU"

--	Mobs

	DESCRIBE.EMPEROR_PENGUIN = {
		GENERIC = "RZĄDZI NIMI ŻELAZNĄ PŁETWĄ",
		HOSTILE = "A WIĘC JA ICH ZDOMINUJĘ MOJĄ ŻELAZNĄ DŁONIĄ",
	}
	DESCRIBE.EMPEROR_PENGUIN_GUARD = "TY. ZABIERZ MNIE DO SWOJEGO \"PRZYWÓDCY\""
    DESCRIBE.MOOSE_POLAR = {
        GENERIC = "HA HA. IDIOTA. HA HA",
        ANTLER = "IMPONUJĄCA OCHRONA. SZKODA, ŻE MARNOWANA NA GŁUPIE ORGANIAKI",
    }
    DESCRIBE.MOOSE_SPECTER = "MUSISZ BYĆ COŚ WARTY, MARTWY"
    DESCRIBE.OCEANFISH_MEDIUM_POLAR1 = "O WIELE BARDZIEJ WARTOŚCIOWY NIŻ JAKAŚ ZŁOTA RYBKA"
    DESCRIBE.POLARBEAR = {
        DEAD = "TWOJA ŚMIERĆ BYŁA PRZEWIDZIANA, MIĘSAKU",
        ENRAGED = "MIĘSAK WCHODZI W TRYB PRZETAKTOWANIA!",
        FOLLOWER = "KŁOŃ SIĘ MI",
        GENERIC = "WYKAZUJE UMIARKOWANE ŚLADY INTELIGENCJI",
    }
    DESCRIBE.POLARFLEA = {
        GENERIC = "NIE POSIADAM DLA WAS SKÓRY, PIJAWKI",
        HELD_INV = "PO CO JE PODNIOSŁEM?",
        HELD_BACKPACK = "GRATULACJE. JESTEŚ TERAZ ZUŻYWALNYM SPRZYMIERZEŃCEM",
    }
    DESCRIBE.POLARFOX = {
        FOLLOWER = "PRZESTAŃ ZA MNĄ CHODZIĆ",
        FRIEND = "ZNOWU TY",
        GENERIC = "TWOJA URODA CIĘ NIE OCALI",
    }
    DESCRIBE.POLARWARG = "WYKAZUJE WYSOKĄ ADAPTACYJNOŚĆ DO SWOJEGO OTOCZENIA"

--	Buildings

	DESCRIBE.CHESSPIECE_EMPEROR_PENGUIN_FRUITY = "NIE BĘDĘ TOLEROWAŁ TAKIEJ NIEPRZYWOITOŚCI W MOIM ZAMKU"
	DESCRIBE.CHESSPIECE_EMPEROR_PENGUIN_JUGGLE = "POZBĄDŹCIE SIĘ TEGO GŁUPCA, JA JESTEM LEPSZYM WZOREM DO NAŚLADOWANIA"
	DESCRIBE.CHESSPIECE_EMPEROR_PENGUIN_MAGESTIC = "UWAGA: PRÓBA ZASTRASZENIA POPRZEZ WYCIĄGANIE KOŃCZYN"
	DESCRIBE.CHESSPIECE_EMPEROR_PENGUIN_SPIN = "WIĘCEJ BEZSENSOWNYCH DEKORACJI ICH BEZSENSOWNEGO PRZYWÓDCY"
    DESCRIBE.POLAR_BRAZIER = {
        GENERIC = "WYSOKIE NOGI TO JEDNO Z ROZWIĄZAŃ NA UNIKANIE ŚNIEGU",
        ON = "OGIEŃ AKTYWOWANY",
    }
    DESCRIBE.POLAR_BRAZIER_ITEM = "PALENISKO, WERSJA PRZENOŚNA"
    DESCRIBE.POLAR_THRONE = "KTOŚ TU MYŚLI, ŻE JEST LEPSZY BO JEST JEGO"
    DESCRIBE.POLAR_THRONE_GIFTS = "WYNIKI ANALIZY MÓWIĄ, ŻE JEST DLA MNIE"
    DESCRIBE.POLARAMULET_STATION = {
        GENERIC = "SUNIE W DÓŁ ZA 3...",
        OPEN = "MOŻESZ ZACZĄĆ OD SWOICH ZĘBÓW NA POCZĄTEK",
    }
    DESCRIBE.POLARBEARHOUSE = {
        BURNT = "TERAZ WYGLĄDA LEPIEJ",
        GENERIC = "JEGO ROZMIAR W PORÓWNANIU Z JEGO MIESZKAŃCEM PRZECZY LOGICE",
    }
    DESCRIBE.POLARICE_PLOW = "ZAGROŻENIE! NADCIĄGAJĄCA WODA"
    DESCRIBE.POLARICE_PLOW_ITEM = "ODMRAŻANIE RYB BYŁOBY DLA NICH PRZYSŁUGĄ"
	DESCRIBE.TOWER_POLAR_FLAG = "JA NIE SALUTUJĘ"
	DESCRIBE.TOWER_POLAR_FLAG_ITEM = "BEZUŻYTECZNE"
	DESCRIBE.RAINOMETER.POLARSTORM = "BRACIE, DLACZEGO JESTEŚ TAKI PRZERAŻONY?"
	DESCRIBE.WINTEROMETER.POLARSTORM = "NIE MARTW SIĘ, KOLEGO, JESTEŚMY GOTOWI NA TO CO NADCHODZI"

--	Items

    --	Food
    DESCRIBE.DRYICECREAM = "LODY BEZ WODY? SŁUGUSIE, CHYBA POSTANOWIĘ CIEBIE OSZCZĘDZIĆ"
    DESCRIBE.ICELETTUCE = "ZADEPCZE CIE"
    DESCRIBE.ICEBURRITO = "BRAKUJE MU NAJWAŻNIEJSZEGO SKŁADNIKA. FAZOLI."
    DESCRIBE.POLARCRABLEGS = "ROZŁOŻONE I GOTOWE DO SPOŻYCIA"

    --	Crafting
    DESCRIBE.BLUEGEM_OVERCHARGED = "TAK... DUŻO... 01001101 01001111 01000011 01011001"
    DESCRIBE.BLUEGEM_SHARDS = "DROBNA SYGNATURA ENERGII. WYMAGANA REKOMBINACJA"
	DESCRIBE.EMPEROR_EGG = "JAJO!? JAJO?!"
    DESCRIBE.MOOSE_POLAR_ANTLER = "CHCĘ WIĘCEJ"
    DESCRIBE.POLAR_DRYICE = "LÓD, ODSĄCZONY Z CAŁEJ SWOJEJ OBRZYDLIWEJ WODY"
    DESCRIBE.POLARBEARFUR = "GŁUPI MIĘSAK ZGUBIŁ SWOJE OCIEPLENIE"
    DESCRIBE.POLARWARGSTOOTH = "ZIMNY I ZABÓJCZY, JAK JA"

    --	Equipments
    DESCRIBE.ANTLER_TREE_STICK = "TWOJE KOŃCZYNY BĘDĄ SŁUŻYĆ MI, DRZEWO"
    DESCRIBE.ARMORPOLAR = "NIEPRZEBIJALNY PUCH"
	DESCRIBE.COMPASS_POLAR = "CHCE SIĘ WYDOSTAĆ, DOTRZEĆ DO TEGO, POCZUĆ TO"
	DESCRIBE.EMPEROR_PENGUINHAT = "NIE ZGODZĘ SIĘ NA NOSZENIE TEGO"
    DESCRIBE.FROSTWALKERAMULET = "HA HA. WYPCHAJ SIĘ, GŁUPIA WODO"
    DESCRIBE.ICICLESTAFF = "ŚMIERĆ Z NIEBIOS"
    DESCRIBE.POLAR_SPEAR = "JEST ZIMNY I ŚMIERCIONOŚNY. PERFEKCYJNIE"
    DESCRIBE.POLARAMULET = "PRZYGOTUJĘ SETKI- NIE, TYSIĄCE TAKICH"
    DESCRIBE.POLARBEARHAT = "ZAPEWNIA WYSTARCZAJĄCĄ OCHRONĘ DLA NARZĄDU WZROKOWEGO"
    DESCRIBE.POLARCROWNHAT = "JEST W PORZĄDKU, DOPÓKI SIĘ NIE COFNIE DO WODNEJ KORONY"
    DESCRIBE.POLARFLEA_SACK = "WYPUSZCZACZ AWARYJNYCH SŁUGUSÓW"
    DESCRIBE.POLARICESTAFF = "Z DROGI, MIĘSAKI"
    DESCRIBE.POLARMOOSEHAT = "ODRAŻAJĄCY MODÓŁ CIEPLNO-CZEREPOWY"
	DESCRIBE.WINTERS_FISTS = "MÓJ PREZENT DLA WAS, MIĘSAKI"

    --	Others
    DESCRIBE.ARCTIC_FOOL_FISH = "MAM NIBY TO PRZYCZEPIĆ DO MIĘSAKÓW I SIĘ Z NICH ŚMIAĆ? DLA MNIE PASUJĘ"
    DESCRIBE.POLARGLOBE = {
        GENERIC = "MĘSAKI SĄ TAK ŁATWO ROZBAWIONE",
        INUSE = "...JAK?",
        REFUEL = "POTRZEBUJE PONOWNEGO NAŁADOWANIA",
    }
    DESCRIBE.OCEANFISH_IN_ICE = "WYJĄTKOWO GŁUPIA RYBA"
    DESCRIBE.POLARICEPACK = "ULEPSZENIE CHŁODZĄCE DLA JEDNOSTEK MAGAZYNOWYCH"
    DESCRIBE.POLARTRINKET_1 = "ŻAŁOSNY GNOM PRÓBUJE OCIEPLIĆ SIĘ KAMIENIAMI"
    DESCRIBE.POLARTRINKET_2 = "NIE ZNOSZĘ PEWNEJ JEJ ANALOGII"
    DESCRIBE.TRAP_POLARTEETH = "PRZEBIJAK STÓP V2.0"
    DESCRIBE.TURF_POLAR_CAVES = "ZIMNA ZIEMIA"
    DESCRIBE.TURF_POLAR_DRYICE = "ZIMNA ZIEMIA"
    DESCRIBE.WALL_POLAR = "ODPOWIEDNIA OCHRONA"
    DESCRIBE.WALL_POLAR_ITEM = "ZIMNA OCHRONA"
    DESCRIBE.WINTER_ORNAMENTPOLAR = "TEN JEST DLA MNIE SZCZEGÓLNIE ODPYCHAJĄCY"
    DESCRIBE.WX78MODULE_NAUGHTY = "PO CO ZAPRZESTAĆ NA USUWANIU MIĘSAKÓW, JEŚLI MOGĘ JE RÓWNIEŻ OBRAŻAĆ"