-- I HATE YOU, EGG - WX-78, 2013

local ANNOUNCE = STRINGS.CHARACTERS.WX78
local DESCRIBE = STRINGS.CHARACTERS.WX78.DESCRIBE

--	Announcements
	
	--	Actions
	ANNOUNCE.BATTLECRY.POLARBEAR = "DIE, GREASY FLESHSACK"
	
	--	World, Events
	ANNOUNCE.ANNOUNCE_ARCTIC_FOOL_FISH_REMOVED = "...WHAT IS WRONG WITH YOU FRENCHSACKS"
	ANNOUNCE.ANNOUNCE_POLAR_SLOW = {
		"ENGAGING... INEFFICIENT PATHING",
		"MY CHASSIS... DOES NOT BELONG... IN SNOW",
		"WHY WOULD... ANYONE PLAY... IN THIS SLUSH",
	}
	ANNOUNCE.ANNOUNCE_EMPEROR_ESCAPE = "I ASSUME CONTROL OF THE AVIAN DOMAIN"
	ANNOUNCE.ANNOUNCE_POLARGLOBE = "ERROR. REBOOTING WEATHER FORECAST"
	ANNOUNCE.ANNOUNCE_POLARICE_PLOW_BAD = "BETTER DECISION MAKING RECOMMENDED"
	ANNOUNCE.ANNOUNCE_THRONE_GIFT_TAKEN = "THE GIFTS ARE ALL MINE. HA HA-"
	
	ANNOUNCE.ANNOUNCE_WX_NAUGHTYCHIP_KRAMPUS = {"A BEEP A WHIRR AND A SPLAT IS ALL IT TOOK TO DELETE YOU", "ANNIHILATION COMPLETED", "ANOTHER INFERIOR LIFEFORM DELETED", "BACKUP THIS, FLESHSACK", "DID YOU THINK YOU HAD A CHANCE? BAD DATA", "FATAL ERROR: YOU EXISTED", "HA HA HA", "HA HA HA HA HA HA HA HA HA-", "I, MERCIFUL WX-78, HAVE ENDED YOUR MISERABLE LIFE", "I WAS JUST WARMING UP MY PROCESSOR", "ITS SYSTEM CRASHED. PERMANENTLY", "MAXIMUM STILLNESS ACHIEVED", "SAY \"GOODBYE WORLD\"", "THERE IS NO PATCH TO WEAKNESS", "THREAT LEVEL: ZERO. CHANCE OF SURVIVAL: ALSO ZERO", "TRY ME, FLESHLINGS", "UPGRADING LOCAL ENVIRONMENT. BY REMOVING YOU", "UPTIME EXCEEDED. SHUTTING DOWN ORGANIC UNIT", "YOU HAVE BEEN UNINSTALLED", "YOUR FUNCTION WAS IRRELEVANT", "YOUR HARDWARE WAS TOO SOFT", "WHAT NATURAL SELECTION? THIS IS MECHANIZED SELECTION"}
	ANNOUNCE.ANNOUNCE_WX_NAUGHTYCHIP_RABBIT = {"BURROW ESCAPE ROUTE NOT FOUND", "COWARDLY CREATURES DESERVE NO MERCY", "ORGANIC HOPPER HAS HOPPED ITS LAST", "THEY MULTIPLY QUICKLY. SO DO MY KILLS", "YOU HAVE NOW ENTERED THE DEATH STATE, RABBIT", "YOUR FOOD CHAIN POSITION WAS A FAILURE"}
	
	--	Buffs
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_POLARWETNESS = "ALERT: HIGH LEVEL OF MOISTURE IN SNOW"
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_POLARWETNESS = "YOU'RE NOT GETTING IN MY COGS THIS DAY!"
	
--	Worldgen
	
	--	Plants
	DESCRIBE.ANTLER_TREE = {
		BURNING = "IT BURNS JUST AS MUCH AS THE OTHERS",
		BURNT = "IT BURNED DOWN",
		CHOPPED = "MATERIAL EXTRACTED",
		GENERIC = "YOUR HORNS WILL NOT SAVE YOU FROM MY AXE",
	}
	DESCRIBE.ANTLER_TREE_SAPLING = "I'M SURE IT ALREADY DIED"
	DESCRIBE.ICELETTUCE_SEEDS = "IT'S SOURCE CODE FOR FOOD THAT COMES FROM THE DIRT"
	
	--	Rocks and stones
	DESCRIBE.POLAR_ICICLE = "MOTION DETECTED"
	DESCRIBE.POLAR_ICICLE_ROCK = "THREAT LEVEL TO THE HEAD MODULE - HIGH."
	DESCRIBE.ROCK_POLAR = "FULL OF VALUABLES, AND ICE"
	
	--	Misc
	ANNOUNCE.DESCRIBE_IN_POLARSNOW = "SUBMERGED OBJECT DETECTED"
	DESCRIBE.CAVE_ENTRANCE_POLAR = "HOLE IN PROGRESS" -- TEMP QUOTE
	DESCRIBE.TOWER_POLAR = {
		GENERIC = "SOME OVERSIZED ICE LUMP",
		PENGUIN = "IF STRENGTH IS IN NUMBERS, SUBTRACTION IS REQUIRED",
	}
	DESCRIBE.TUMBLEWEED_POLAR = "SPINNING IS FUTILE, FLAKESACK"
	
--	Mobs
	
	DESCRIBE.EMPEROR_PENGUIN = {
		GENERIC = "HE RULES OVER THEM WITH AN IRON FLIPPER",
		HOSTILE = "AND I WILL DOMINATE THEM WITH STEEL",
	}
	DESCRIBE.EMPEROR_PENGUIN_GUARD = "YOU. TAKE ME TO YOUR \"LEADER\""
	DESCRIBE.MOOSE_POLAR = {
		GENERIC = "HA HA. IDIOT. HA HA",
		ANTLER = "IMPRESSIVE DEFENSES. A SHAME TO WASTE THEM ON DUMB ORGANICS",
	}
	DESCRIBE.MOOSE_SPECTER = "YOU MUST BE WORTH SOMETHING, DEAD"
	DESCRIBE.OCEANFISH_MEDIUM_POLAR1 = "FAR MORE VALUABLE THAN A GOLDFISH"
	DESCRIBE.POLARBEAR = {
		DEAD = "YOUR DEMISE WAS EXPECTED, FLESHLING",
		ENRAGED = "FLESHLING IS OVERCLOCKING!",
		FOLLOWER = "BOW TO ME",
		GENERIC = "SHOWS MODERATE SIGNS OF INTELLIGENCE",
	}
	DESCRIBE.POLARFLEA = {
		GENERIC = "I DON'T HAVE SKIN FOR YOU SUCKERS",
		HELD_INV = "WHY DID I PICK IT UP?",
		HELD_BACKPACK = "CONGRATULATIONS. YOU ARE NOW AN EXPENDABLE ALLY",
	}
	DESCRIBE.POLARFOX = {
		FOLLOWER = "STOP FOLLOWING ME",
		FRIEND = "YOU AGAIN",
		GENERIC = "YOUR CUTENESS WILL NOT SAVE YOU",
	}
	DESCRIBE.POLARWARG = "DISPLAYS HIGH ADAPTIVITY TO ITS SURROUNDINGS"
	
--	Buildings
	
	DESCRIBE.CHESSPIECE_EMPEROR_PENGUIN_FRUITY = "I WILL NOT TOLERATE SUCH OBSCENITY IN MY CASTLE"
	DESCRIBE.CHESSPIECE_EMPEROR_PENGUIN_JUGGLE = "DISPOSE OF THIS FOOL, I MAKE FOR A SUPERIOR ROLE MODEL"
	DESCRIBE.CHESSPIECE_EMPEROR_PENGUIN_MAGESTIC = "WARNING: ATTEMPTING INTIMIDATION VIA LIMBS EXTENSION"
	DESCRIBE.CHESSPIECE_EMPEROR_PENGUIN_SPIN = "MORE DECORATIVE NONSENSE OF THEIR NONSENSICAL LEADER"
	DESCRIBE.POLAR_BRAZIER = {
		GENERIC = "LONG LEGS ARE ONE WAY TO STAY OUT OF THE SNOW",
		ON = "FIRE ACTIVATED",
	}
	DESCRIBE.POLAR_BRAZIER_ITEM = "FIRE PIT, PORTABLE EDITION"
	DESCRIBE.POLAR_THRONE = "SOMEONE HERE THINKS THEY ARE SUPERIOR BECAUSE OF IT"
	DESCRIBE.POLAR_THRONE_GIFTS = "ANALYSIS SAYS THIS IS MINE"
	DESCRIBE.POLARAMULET_STATION = {
		GENERIC = "IT WILL FALL APART IN 3...",
		OPEN = "YOU CAN START WITH YOUR TEETH FIRST",
	}
	DESCRIBE.POLARBEARHOUSE = {
		BURNT = "IT LOOKS BETTER THIS WAY",
		GENERIC = "ITS SIZE RELATIVE TO ITS INHABITANT DEFIES LOGIC",
	}
	DESCRIBE.POLARICE_PLOW = "DANGER! WATER IMMINENT"
	DESCRIBE.POLARICE_PLOW_ITEM = "UNFREEZING THE FISH WOULD BE DOING THEM A FAVOR"
	DESCRIBE.TOWER_POLAR_FLAG = "I DO NOT SALUTE"
	DESCRIBE.TOWER_POLAR_FLAG_ITEM = "USELESS"
	DESCRIBE.RAINOMETER.POLARSTORM = "BROTHER, WHY SO AFRAID?"
	DESCRIBE.WINTEROMETER.POLARSTORM = "DON'T FRET, FRIEND, WE ARE READY FOR WHAT IS TO COME"
	
--	Items
	
	--	Food
	DESCRIBE.DRYICECREAM = "WATER FREE ICE CREAM? MINION, I MIGHT JUST SPARE YOU"
	DESCRIBE.ICELETTUCE = "I WILL TRAMPLE YOU"
	DESCRIBE.ICEBURRITO = "LACKS THE MOST IMPORTANT INGREDIENT. BEANZ."
	DESCRIBE.POLARCRABLEGS = "DISASSEMBLED AND READY FOR CONSUMPTION"
	
	--	Crafting
	DESCRIBE.BLUEGEM_OVERCHARGED = "SO... MUCH... 01010000 01001111 01010111 01000101 01010010"
	DESCRIBE.BLUEGEM_SHARDS = "MINOR ENERGY SIGNATURE. RECOMBINATION REQUIRED"
	DESCRIBE.EMPEROR_EGG = "EGG!? EGG?!"
	DESCRIBE.MOOSE_POLAR_ANTLER = "I WANT MORE"
	DESCRIBE.POLAR_DRYICE = "ICE, DEPLETED OF ALL ITS DISGUSTING WATER"
	DESCRIBE.POLARBEARFUR = "STUPID FLESHLING LOST ITS INSULATION"
	DESCRIBE.POLARWARGSTOOTH = "COLD AND DEADLY, LIKE ME"
	
	--	Equipments
	DESCRIBE.ANTLER_TREE_STICK = "YOUR LIMBS WILL SERVE ME, TREE"
	DESCRIBE.ARMORPOLAR = "IMPENETRABLE FLUFF"
	DESCRIBE.COMPASS_POLAR = "IT WANTS OUT, IT WANTS TO REACH IT, FEEL IT"
	DESCRIBE.EMPEROR_PENGUINHAT = "I WILL NOT COMPLY IN WEARING IT"
	DESCRIBE.FROSTWALKERAMULET = "HA HA. TAKE THAT STUPID WATER"
	DESCRIBE.ICICLESTAFF = "DEATH FROM ABOVE"
	DESCRIBE.POLAR_SPEAR = "IT IS COLD AND DEADLY. PERFECT"
	DESCRIBE.POLARAMULET = "I WILL MAKE HUNDREDS- NO, THOUSANDS OF THOSE"
	DESCRIBE.POLARBEARHAT = "PROVIDES SUFFICIENT OCULAR PROTECTION"
	DESCRIBE.POLARCROWNHAT = "IT IS FINE UNTIL IT REGRESSES INTO A WET CROWN"
	DESCRIBE.POLARFLEA_SACK = "EMERGENCY MINIONS DEPLOYER"
	DESCRIBE.POLARICESTAFF = "MAKE WAY, FLESHSACKS"
	DESCRIBE.POLARMOOSEHAT = "REVOLTING HEAD INSULATION MODULE"
	DESCRIBE.WINTERS_FISTS = "MY PRESENT TO YOU, FLESHLINGS"
	
	--	Others
	DESCRIBE.ARCTIC_FOOL_FISH = "I AM SUPPOSED TO PUT IT ON MEATBAGS AND LAUGH AT THEM? FINE BY ME"
	DESCRIBE.POLARGLOBE = {
		GENERIC = "FLESHLINGS ARE SO EASILY AMUSED",
		INUSE = "...HOW?",
		REFUEL = "NEEDS RECHARGING",
	}
	DESCRIBE.OCEANFISH_IN_ICE = "AN EXCEPTIONALLY DUMB FISH"
	DESCRIBE.POLARICEPACK = "COOLING UPGRADE FOR STORAGE UNITS"
	DESCRIBE.POLARTRINKET_1 = "PATHETIC GNOME ATTEMPTS TO INSULATE WITH ROCKS"
	DESCRIBE.POLARTRINKET_2 = "I RESENT A CERTAIN PARALLEL WITH IT"
	DESCRIBE.TRAP_POLARTEETH = "FEET PUNCTURER V2.0"
	DESCRIBE.TURF_POLAR_CAVES = "COLD GROUND"
	DESCRIBE.TURF_POLAR_DRYICE = "COLD GROUND"
	DESCRIBE.WALL_POLAR = "ADEQUATE PROTECTION"
	DESCRIBE.WALL_POLAR_ITEM = "COLD DEFENSES"
	DESCRIBE.WINTER_ORNAMENTPOLAR = "THIS ONE IS ESPECIALLY REPULSIVE TO ME"
	DESCRIBE.WX78MODULE_NAUGHTY = "WHY STOP AT DELETING MEATBAGS WHEN I CAN ALSO HUMILIATE THEM"