local ANNOUNCE = STRINGS.CHARACTERS.WX78
local DESCRIBE = STRINGS.CHARACTERS.WX78.DESCRIBE

--	Announcements
	
	--	Actions
	ANNOUNCE.BATTLECRY.POLARBEAR = "MEURS, SAC DE CHAIR GRAISSEUX"
	
	--	World, Events
	ANNOUNCE.ANNOUNCE_POLAR_SLOW = {
		"ACTIVATION... D'UN CHEMINEMENT INEFFICACE",
		"MON CHÂSSIS... N'A RIEN À FAIRE... DANS LA NEIGE",
		"QUI POURRAIT TROUVER... DU PLAISIR DANS... CETTE BOUILLIE",
	}
	ANNOUNCE.ANNOUNCE_POLARGLOBE = "ERREUR. RÉINITIALISATION DES PRÉVISIONS MÉTÉO"
	ANNOUNCE.ANNOUNCE_POLARICE_PLOW_BAD = "MEILLEURE PRISE DE DÉCISION RECOMMANDÉE"
	ANNOUNCE.ANNOUNCE_THRONE_GIFT_TAKEN = "LES CADEAUX SONT À MOI. TOUS À MOI. HA HA-"
	
	ANNOUNCE.ANNOUNCE_WX_NAUGHTYCHIP_KRAMPUS = {"UN BIP, UN VROOM ET UN SPLAT. C'EST TOUT CE QU'IL A FALLU POUR TE SUPPRIMER", "ANNIHILATION COMPLÈTE", "UNE AUTRE FORME DE VIE INFÉRIEURE, ÉLIMINÉE", "BACKUP ÇA, SAC DE VIANDE", "TU PENSAIS AVOIR UNE CHANCE ? TES DONNÉES SONT ERRONÉES", "ERREUR FATALE : TU AS EXISTÉ", "HA HA HA", "HA HA HA HA HA HA HA HA HA-", "MOI, MISÉRICORDIEUX WX-78, AI ABRÉGÉ TA PATHÉTIQUE EXISTENCE", "JE NE FAISAIS QUE ÉCHAUFFER MON PROCESSEUR", "SON SYSTÈME A CRASH. DÉFINITIVEMENT", "IMMOBILITÉ MAXIMALE ATTEINTE", "DIS : «AU REVOIR MONDE»", "IL N'Y A AUCUN PATCH DISPONIBLE POUR LA FAIBLESSE", "NIVEAU DE MENACE : ZÉRO. CHANCE DE SURVIE : ÉGALEMENT ZÉRO", "MESUREZ-VOUS A MOI, CHOSES EN VIANDE", "AMÉLIORATION DE L'ENVIRONNEMENT LOCAL... EN TE SUPPRIMANT", "PÉRIODE D'ESSAI DÉPASSÉ. EXTINCTION DE L'UNITÉ ORGANIQUE", "TU AS ÉTÉ DÉSINSTALLÉ", "TA FONCTION ÉTAIT IRRELEVANTE", "TON HARDWARE ÉTAIT BIEN TROP SOFT", "QUELLE SÉLECTION NATURELLE ? CECI EST UNE SÉLECTION MÉCANISÉE"}
	ANNOUNCE.ANNOUNCE_WX_NAUGHTYCHIP_RABBIT = {"VOIE D'ÉVACUATION AU TERRIER NON TROUVÉE", "LES LÂCHES NE MÉRITENT AUCUNE PITIÉ", "LE SAUTEUR ORGANIQUE A FAIT SON DERNIER SAUT", "ILS SE MULTIPLIENT RAPIDEMENT. MES VICTIMES AUSSI", "TU AS MAINTENANT ATTEINT L'ÉTAT DE MORT, LAPIN", "TON POSITIONNEMENT DANS LA CHAÎNE ALIMENTAIRE ÉTAIT UN ÉCHEC"}
	
	--	Buffs
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_POLARWETNESS = "ALERTE : NIVEAU D'HUMIDITÉ ÉLEVÉ EN NEIGE"
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_POLARWETNESS = "TU NE RENTRERAS PAS DANS MES ENGRENAGES AUJOURD'HUI !"
	
--	Worldgen
	
	--	Plants
	DESCRIBE.ANTLER_TREE = {
		BURNING = "CETTE ARBRE BRÛLE TOUT AUSSI BIEN QUE LES AUTRES",
		BURNT = "IL A BRÛLÉ JUSQU'AU BOUT",
		CHOPPED = "MATÉRIAUX EXTRACTÉS",
		GENERIC = "TES CORNES NE TE SAUVERONT PAS DE MA HACHE",
	}
	DESCRIBE.ICELETTUCE_SEEDS = "C'EST LE CODE SOURCE DE LA NOURRITURE QUI VIENT DE LA TERRE"
	
	--	Rocks and stones
	DESCRIBE.POLAR_ICICLE = "MOUVEMENT DÉTECTÉ"
	DESCRIBE.POLAR_ICICLE_ROCK = "MENACE POUR LE MODULE CÉRÉBRAL : ÉLEVÉ."
	DESCRIBE.ROCK_POLAR = "REMPLI DE MATÉRIAUX DE VALEUR. ET DE GLACE"
	
	--	Misc
	ANNOUNCE.DESCRIBE_IN_POLARSNOW = "OBJET ENFOUI DÉTECTÉ"
	DESCRIBE.TUMBLEWEED_POLAR = "FUIR EST FUTILE, SAC À GLACE"
	
--	Mobs
	
	DESCRIBE.MOOSE_POLAR = {
		GENERIC = "HA HA. IDIOT. HA HA",
		ANTLER = "BELLES DÉFENSES. DOMMAGE QU'ELLES SOIENT GASPILLÉES SUR UN ORGANISME COMME TOI",
	}
	DESCRIBE.MOOSE_SPECTER = "TU DOIS BIEN VALOIR QUELQUE CHOSE, ÉTANT MORT"
	DESCRIBE.OCEANFISH_MEDIUM_POLAR1 = "LARGEMENT PLUS PRÉCIEUX QU'UN POISSON ROUGE"
	DESCRIBE.POLARBEAR = {
		DEAD = "TA MORT ÉTAIT PRÉVUE, CHOSE EN CHAIR",
		ENRAGED = "L'ORGANISME SURCHAUFFE !",
		FOLLOWER = "PROSTERNE-TOI",
		GENERIC = "CETTE CHOSE PRÉSENTE DES SIGNES D'INTELLIGENCE MODÉRÉS",
	}
	DESCRIBE.POLARFLEA = {
		GENERIC = "ET NON, JE N'AI PAS DE PEAU À LAQUELLE S'ACCROCHER, VERMINES",
		HELD_INV = "POURQUOI AI-JE RAMASSÉ ÇA ?",
		HELD_BACKPACK = "FÉLICITATIONS. TU ES DÉSORMAIS UN ALLIÉ SACRIFIABLE",
	}
	DESCRIBE.POLARFOX = {
		FOLLOWER = "ARRÊTE DE ME SUIVRE",
		FRIEND = "ENCORE TOI?",
		GENERIC = "TON CHARME NE TE SAUVERA PAS",
	}
	DESCRIBE.POLARWARG = "IL DÉMONTRE UNE EXCELLENTE ADAPTABILITÉ À SON ENVIRONNEMENT"
	
--	Buildings
	
	DESCRIBE.POLAR_BRAZIER = {
		GENERIC = "DE LONGUES JAMBES SONT UNE SOLUTION POUR RESTER HORS DE LA NEIGE",
		ON = "FEU : ACTIVÉ",
	}
	DESCRIBE.POLAR_BRAZIER_ITEM = "UN FOYER, VERSION PORTABLE"
	DESCRIBE.POLAR_THRONE = "QUELQU'UN SE CROIT SUPÉRIEURE À CAUSE DE CELA"
	DESCRIBE.POLAR_THRONE_GIFTS = "ANALYSE TERMINÉE : CES CADEAUX M'APPARTIENS. TOUS"
	DESCRIBE.POLARAMULET_STATION = {
		GENERIC = "ÉCROULEMENT DANS 3...",
		OPEN = "TU PEUX COMMENCER PAR TES DENTS",
	}
	DESCRIBE.POLARBEARHOUSE = {
		BURNT = "ELLE EST MIEUX COMME ÇA",
		GENERIC = "SA TAILLE RELATIVE À SON HABITANT DÉFIE TOUTE LOGIQUE",
	}
	DESCRIBE.POLARICE_PLOW = "DANGER : EAU IMMINENTE"
	DESCRIBE.POLARICE_PLOW_ITEM = "DÉGELER LES POISSONS SERAIT LEUR RENDRE SERVICE"
	
--	Items
	
	--	Food
	DESCRIBE.DRYICECREAM = "UNE GLACE SANS EAU ? SOUS-FIFRE, JE DEVRAIS TE GARDER EN VIE"
	DESCRIBE.ICELETTUCE = "JE VAIS TE PIÉTINER, SALADE"
	DESCRIBE.ICEBURRITO = "IL MANQUE L'INGRÉDIENT LE PLUS IMPORTANT : LES BEANZ"
	DESCRIBE.POLARCRABLEGS = "DÉMONTÉES ET PRÊTES À LA CONSOMMATION"
	
	--	Crafting
	DESCRIBE.BLUEGEM_OVERCHARGED = "TANT... DE... 01010000 01001111 01010111 01000101 01010010"
	DESCRIBE.BLUEGEM_SHARDS = "SIGNATURE ÉNERGÉTIQUE MINEURE. COMBINAISON REQUISE"
	DESCRIBE.MOOSE_POLAR_ANTLER = "IL M'EN FAUT ENCORE PLUS"
	DESCRIBE.POLAR_DRYICE = "DE LA GLACE, PRIVÉE DE TOUTE SON EAU DÉGOÛTANTE"
	DESCRIBE.POLARBEARFUR = "LE SAC À VIANDE A PERDU SON ISOLATION"
	DESCRIBE.POLARWARGSTOOTH = "FROID ET MORTEL, COMME MOI"
	
	--	Equipments
	DESCRIBE.ANTLER_TREE_STICK = "TES MEMBRES ME SERVIRONT, ARBRE"
	DESCRIBE.ARMORPOLAR = "TOUT PLEIN DE PELUCHE IMPÉNÉTRABLE"
	DESCRIBE.FROSTWALKERAMULET = "HA HA. PRENDS ÇA, FOUTUE EAU"
	DESCRIBE.ICICLESTAFF = "LA MORT VIENT DU CIEL"
	DESCRIBE.POLAR_SPEAR = "C'EST FROID ET MORTEL. PARFAIT"
	DESCRIBE.POLARAMULET = "JE VAIS EN FABRIQUERAI DES CENTAINES... NON, DES MILLIERS"
	DESCRIBE.POLARBEARHAT = "UNE PROTECTION OCULAIRE DIFFICILEMENT ACCEPTABLE"
	DESCRIBE.POLARCROWNHAT = "C'EST OK JUSQU'À CE QUE CELA DEVIENNE UNE COURONNE TREMPÉE"
	DESCRIBE.POLARFLEA_SACK = "DÉPLOYEUR DE SOUS-FIFRES D'URGENCE"
	DESCRIBE.POLARICESTAFF = "DÉGAGEZ DE MON CHEMIN, SACS À VIANDE"
	DESCRIBE.POLARMOOSEHAT = "UN MODULE D'ISOLATION CRÂNIENNE RÉPUGNANT"
	
	--	Others
	DESCRIBE.POLARGLOBE = {
		GENERIC = "LES CHOSES EN VIANDE SONT SI FACILEMENT DISTRAITES",
		INUSE = "... COMMENT ?",
		REFUEL = "PLUS ASSEZ DE NEIGE",
	}
	DESCRIBE.OCEANFISH_IN_ICE = "UN POISSON EXCEPTIONNELLEMENT STUPIDE"
	DESCRIBE.POLARICEPACK = "AMÉLIORATION DE REFROIDISSEMENT POUR UNITÉS DE STOCKAGE"
	DESCRIBE.POLARTRINKET_1 = "CE GNOME PATHÉTIQUE ESSAYE DE SE RÉCHAUFFER AVEC DE LA PIERRE"
	DESCRIBE.POLARTRINKET_2 = "JE DÉTESTE UNE CERTAINE RESSEMBLANCE ENTRE NOUS"
	DESCRIBE.TRAP_POLARTEETH = "PERFORATEUR DE PIEDS V2.0"
	DESCRIBE.TURF_POLAR_CAVES = "MORCEAUX DE SOL FROID"
	DESCRIBE.TURF_POLAR_DRYICE = "MORCEAUX DE SOL FROID"
	DESCRIBE.WALL_POLAR = "PROTECTION ADÉQUATE"
	DESCRIBE.WALL_POLAR_ITEM = "UNE DÉFENSE GLACÉE"
	DESCRIBE.WINTER_ORNAMENTPOLAR = "CELUI-CI ME RÉPUGNE PARTICULIÈREMENT"
	DESCRIBE.WX78MODULE_NAUGHTY = "POURQUOI ME LIMITER À SUPPRIMER LES ORGANISMES QUAND JE PEUX AUSSI LES HUMILIER ?"