local ANNOUNCE = STRINGS.CHARACTERS.WORMWOOD
local DESCRIBE = STRINGS.CHARACTERS.WORMWOOD.DESCRIBE

--	Announcements
	
	--	Actions
	ANNOUNCE.BATTLECRY.POLARBEAR = "攻擊！"
	
	--	World, Events
	ANNOUNCE.ANNOUNCE_POLAR_SLOW = {
		"不是像這裡這樣……",
		"冷！冷！",
		"不喜歡冷！",
	}
	ANNOUNCE.ANNOUNCE_POLARGLOBE = "哎喲 哎喲 哎喲！"
	ANNOUNCE.ANNOUNCE_POLARICE_PLOW_BAD = "不在這裡？"
	ANNOUNCE.ANNOUNCE_THRONE_GIFT_TAKEN = "好耶！"
	
	--	Buffs
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_POLARWETNESS = "不！冷！"
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_POLARWETNESS = "啊哈，雪全沒了"
	
--	Worldgen
	
	--	Plants
	DESCRIBE.ANTLER_TREE = {
		BURNING = "火！不！",
		BURNT = "雪不夠嗎？",
		CHOPPED = "(嘆氣) 為什麼要打架？",
		GENERIC = "為什麼要長角？",
	}
	DESCRIBE.ICELETTUCE_SEEDS = "寒冷的小寶寶"
	
	--	Rocks and stones
	DESCRIBE.POLAR_ICICLE = "在生長嗎？"
	DESCRIBE.POLAR_ICICLE_ROCK = "大掉落"
	DESCRIBE.ROCK_POLAR = "冰中被困的亮晶晶？怎麼回事？"
	
	--	Misc
	ANNOUNCE.DESCRIBE_IN_POLARSNOW = "嗯？"
	DESCRIBE.TUMBLEWEED_POLAR = "慢一點！"
	
--	Mobs
	
	DESCRIBE.MOOSE_POLAR = {
		GENERIC = "教訓學到了。不應該和朋友打架",
		ANTLER = "有大樹枝！",
	}
	DESCRIBE.MOOSE_SPECTER = "樹枝冷了嗎？"
	DESCRIBE.OCEANFISH_MEDIUM_POLAR1 = "閃亮的咕嚕咕嚕！"
	DESCRIBE.POLARBEAR = {
		DEAD = "呃哦……",
		ENRAGED = "需要冷靜一下！",
		FOLLOWER = "冷冷的毛茸茸好朋友",
		GENERIC = "哦，冷冷的毛茸茸！",
	}
	DESCRIBE.POLARFLEA = {
		GENERIC = "不想再來一次！",
		HELD_INV = "會很痛",
		HELD_BACKPACK = "交新朋友",
	}
	DESCRIBE.POLARFOX = {
		FOLLOWER = "嘘……現在沒事了",
		FRIEND = "嗨，朋友！記得我嗎？",
		GENERIC = "啊！過來，過來！",
	}
	DESCRIBE.POLARWARG = "很冷的大狗狗"
	
--	Buildings
	
	DESCRIBE.POLAR_BRAZIER = {
		GENERIC = "冷嗎？",
		ON = "熱！",
	}
	DESCRIBE.POLAR_BRAZIER_ITEM = "留著以後用的火。"
	DESCRIBE.POLAR_THRONE = "坐不著的地方"
	DESCRIBE.POLAR_THRONE_GIFTS = "給我的？"
	DESCRIBE.POLARAMULET_STATION = {
		GENERIC = "有人在家嗎？",
		OPEN = "你好……！你好？",
	}
	DESCRIBE.POLARBEARHOUSE = {
		BURNT = "聞起來有魚腥味",
		GENERIC = "咕嚕咕嚕的房子",
	}
	DESCRIBE.POLARICE_PLOW = "很快就會有水！"
	DESCRIBE.POLARICE_PLOW_ITEM = "挖挖挖洞?"
	
--	Items
	
	--	Food
	DESCRIBE.DRYICECREAM = "（舔）嗚！（舔）嗚—"
	DESCRIBE.ICELETTUCE = "朋友想要大大的溫暖擁抱嗎？"
	DESCRIBE.ICEBURRITO = "咕嚕咕嚕在捲裡睡覺"
	DESCRIBE.POLARCRABLEGS = "不會讓腿逃掉"
	
	--	Crafting
	DESCRIBE.BLUEGEM_OVERCHARGED = "變得更冷"
	DESCRIBE.BLUEGEM_SHARDS = "變得小小的冷"
	DESCRIBE.MOOSE_POLAR_ANTLER = "壞掉了"
	DESCRIBE.POLAR_DRYICE = "用來做新鮮的小吃"
	DESCRIBE.POLARBEARFUR = "暖和"
	DESCRIBE.POLARWARGSTOOTH = "冷！哇！"
	
	--	Equipments
	DESCRIBE.ANTLER_TREE_STICK = "掉了什麼？"
	DESCRIBE.ARMORPOLAR = "好毛茸茸的衣服"
	DESCRIBE.FROSTWALKERAMULET = "現在是水，現在是石頭？"
	DESCRIBE.ICICLESTAFF = "會造成痛痛雨"
	DESCRIBE.POLAR_SPEAR = "尖尖的"
	DESCRIBE.POLARAMULET = "痛痛的脖子東西"
	DESCRIBE.POLARBEARHAT = "不想被吃掉！"
	DESCRIBE.POLARCROWNHAT = "頭上的東西想要更暖和嗎？"
	DESCRIBE.POLARFLEA_SACK = "暖和！真好"
	DESCRIBE.POLARICESTAFF = "一切都變得冷冷的"
	DESCRIBE.POLARMOOSEHAT = "斧頭朋友？"
	
	--	Others
	DESCRIBE.POLARGLOBE = {
		GENERIC = "嗯……有人碰過嗎？",
		INUSE = "不不不，回去裡面！",
		REFUEL = "終於在睡覺了？",
	}
	DESCRIBE.OCEANFISH_IN_ICE = "需要一點火。"
	DESCRIBE.POLARICEPACK = "能保持肚子裡的東西更多？"
	DESCRIBE.POLARTRINKET_1 = "舒適的小家伙"
	DESCRIBE.POLARTRINKET_2 = "尖帽女孩需要幫助嗎？"
	DESCRIBE.TRAP_POLARTEETH = "寒冷的尖刺"
	DESCRIBE.TURF_POLAR_CAVES = "冰"
	DESCRIBE.TURF_POLAR_DRYICE = "冰"
	DESCRIBE.WALL_POLAR = "滑滑的"
	DESCRIBE.WALL_POLAR_ITEM = "啜飲"
	DESCRIBE.WINTER_ORNAMENTPOLAR = "不想讓朋友冷……哦。不冷"
	DESCRIBE.WX78MODULE_NAUGHTY = "嗶嗶啵啵"